repos:
    - repo: meta
      hooks:
          - id: check-hooks-apply
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: fix-byte-order-marker
          - id: check-added-large-files
            args: [--maxkb=500]
          - id: check-case-conflict
          - id: check-json
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v3.0.0-alpha.4"
      hooks:
          - id: prettier
            additional_dependencies:
                - "prettier@3.0.0-alpha.4"
                - "@trivago/prettier-plugin-sort-imports@v4.0.0"
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.31.0
      hooks:
          - id: eslint
            additional_dependencies:
                - "eslint@v8.31.0"
                - "@sanity/eslint-config-studio@2.0.1"
                - "@typescript-eslint/eslint-plugin@5.48.1"
                - "@typescript-eslint/parser@5.48.1"
                - "eslint-plugin-tsdoc@0.2.17"
                - "typescript@4.9.4"
            files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
            types: [file]
